server:
  port: 8084

spring:
  application:
    name: CONFIGSERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Swaraj2610/microservice-apigateway-config
          clone-on-start: true 