server:
  port: 8084

spring:
  application:
    name: CONFIGSERVER
  cloud:
    config:
      server:
        git:
          uri: <YOUR_GITHUB_REPOSITORY_CONTAINS_CONFIG_FILE>
          clone-on-start: true 
