server:
  port: 8083

spring:
  application:
    name: RATINGSERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: <YOUR_USERNAME>
    password: <YOUR_PASSWORD>
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:configserver:http://localhost:8084

